version: '3'

services:
  backend:
    build:
      context: ./backend
    environment:
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
    ports:
      - "8580:80"
    depends_on:
      - backend
